version: '3'
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg18
    container_name: timescale
    restart: on-failure
    ports:
      - 15432:5432
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: tsdb
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - asp-demo-net
  cache:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '16379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - "./redis/data:/data"
    networks:
      - asp-demo-net
  keycloak:
    image: keycloak/keycloak:26.1.4
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8080:8080"
    volumes:
      - "./keycloak/data:/opt/keycloak/data"
    networks:
      - asp-demo-net

networks:
  asp-demo-net: